### ISSUE TITLE
Resume training

### ISSUE THREAD

**Issue by bagaturchess** [jw1912/bullet#109]
Hi and thanks for the nice project!
I am looking for a way to resume the training, because my machine got crashed and I had to restart it.
Is it possible to resume the training?
Best regards,
Krasimir

**Comment by jw1912** [comment]
@bagaturchess if you have a saved checkpoint, you can do as follows
```rust
let schedule = TrainingSchedule {
    ...
    start_superbatch: resume_from_here_superbatch
    ...
}

trainer.load_from_checkpoint("path/to/checkpoint");

trainer.run(&schedule, &settings);
```

**Comment by bagaturchess** [comment]
Thanks a lot for the answer!
The solution provided looks working.
Best regards,
Krasimir
