### ISSUE TITLE
Question about Positions / Superbatch and Positions

### ISSUE THREAD

**Issue by bagaturchess** [jw1912/bullet#111]
Hi,

I have a question regarding the positions count in the training data:
What happens if the Positions / Superbatch is smaller than the Positions?
I assume that the training will use only the first Positions / Superbatch positions for the training.
Is my assumption correct?

Best regards,
Krasimir

**Comment by jw1912** [comment]
@bagaturchess the superbatch is wholly independent of dataset size, if you have less positions in your dataset than are in one superbatch, the superbatch uses its usual number of positions, wrapping back round to the start of the dataset.

I recommend joining the Engine Programming Discord Server (https://discord.com/invite/F6W6mMsTGN).

**Comment by bagaturchess** [comment]
Thanks for the answer.
Best regards, Krasimir
