### ISSUE TITLE
index out of bounds: the len is 16 but the index is 16

### ISSUE THREAD

**Issue by enfmarinho** [jw1912/bullet#118]
Trying to use bullet to train the NNUE of my chess engine but I'm encountering a problem. When i try to run exemples/simple.rs without make any modification to any of the source code, except for the path of the data_file_path on it. I used a dataset very small just to test bullet, everything is on the format described on bulletformat. The bullet output follows: 
<img width="1680" alt="Screenshot 2024-07-02 at 23 21 09" src="https://github.com/jw1912/bullet/assets/120424205/d20b0446-31c5-4fa7-9812-a1934007d566">
What can i do to fix this ? 
Thanks is advance for the attention and for the great repo! Sorry if this is a bump mistake at my part.

**Comment by enfmarinho** [comment]
To add information, this is part of my dataset file.
<img width="1680" alt="Screenshot 2024-07-02 at 23 32 30" src="https://github.com/jw1912/bullet/assets/120424205/a4c20b9a-df1c-4a32-9013-970b07e53ee7">

**Comment by jw1912** [comment]
@enfmarinho you aren’t using bulletformat, you’re using text format.

From the [wiki](https://github.com/jw1912/bullet/wiki/3.-Data#chessboard):
> Additionally, you can **_convert_** legacy text format as in Marlinflow

**Comment by enfmarinho** [comment]
Got it now, thanks a lot!
