### ISSUE TITLE
CUDA setup documentation

### ISSUE THREAD

**Issue by jdart1** [jw1912/bullet#140]
Should document that CUDA version >=12.2 is required.
Also you need the CUDA_PATH environment variable set, and the CUDA bin directory should be in the PATH.
You may also need to set HOST_CXX. I have HOST_CXX=clang.

**Comment by jw1912** [comment]
Hi @jdart1, I've added the instructions to the [README in the rewrite branch](https://github.com/jw1912/bullet/tree/rewrite?tab=readme-ov-file#backends).
